

language: python

python:
  - '3.7'

# échoue dès qu'une erreur intervient
matrix:
  fast_finish: true

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-demo .
      - docker images
      - docker tag travis-ci-build-mattermost_ws $DOCKER_USERNAME/travis-ci-build-mattermost_ws
      - docker push $DOCKER_USERNAME/travis-ci-build-mattermost_ws
    
    -stage: lint
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-mattermost_ws flake8
    
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-mattermost_ws test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-mattermost_ws coverage
